In [1]:
import torch 
import torch.nn as nn 
import torch.optim as optim
import numpy as np

In [2]:
# model = nn.Sequential(nn.Linear(3, 3), # Define the input layer and hidden layer
#                         nn.ReLU(), # this is the activation function
#                         nn.Linear(3, 1)) # this defines the output layer

In [3]:
# if it is a model with one layer and one nueron 
model = nn.Sequential(nn.Linear(1, 1))

In [4]:
#   losss and optimizer, here losss is criterion because loss is is not callable since it is a tensor object
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [5]:
xs = torch.tensor([[-1.0], [0.0], [1.0], [2.0], [3.0], [4.0]], dtype=torch.float32)

ys = torch.tensor([[-3.0], [-1.0], [1.0], [3.0], [5.0], [7.0]],dtype=torch.float32)

In [6]:
# Data
# Training features ['Years of experience', 'performance score', 'projects completed']
Features = torch.tensor([[1, 60, 2], [2, 65, 3], [3, 70, 4], [4, 72, 5], [5,  78,  6], [6,  82,  7], [7,  85,  8], [8,  88,  9], [9,  92, 10], [10, 95, 12]], dtype=torch.float32)

Salary = torch.tensor([[500], [700], [900], [1100], [1400], [1700], [2000], [2300], [2700], [3200]], dtype=torch.float32)

In [7]:
# TRianing
for _ in range(500):
    size = len(xs)
    optimizer.zero_grad()
    pred = model(xs)
    loss = criterion(pred, ys)
    loss.backward()
    optimizer.step()
    print("Loss = ",loss)
    print(f"Size = {size}")

Loss =  tensor(24.4273, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(19.4295, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(15.4932, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(12.3920, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(9.9480, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(8.0211, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(6.5011, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(5.3013, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(4.3535, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(3.6041, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(3.0108, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(2.5405, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(2.1669, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(1.8695, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(1.6322, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(1.4422, grad_fn=<MseLossBackward0>)
Size = 6
Loss =  tensor(1.2894, grad_fn=<MseL

In [8]:
# Predict
with torch.no_grad():
    print(model(torch.tensor([[10.0]], dtype=torch.float32)))

tensor([[18.9828]])


In [9]:
layer = model[0]

weights = layer.weight.data.numpy()
bias = layer.bias.data.numpy()

weights

array([[1.9975035]], dtype=float32)

In [10]:
bias

array([-0.99226034], dtype=float32)