In [1]:
import torch 
import torch.nn as nn 
import torch.optim as optim
import numpy as np

In [ ]:
# model = nn.Sequential(nn.Linear(3, 3), # Define the input layer and hidden layer
#                         nn.ReLU(), # this is the activation function
#                         nn.Linear(3, 1)) # this defines the output layer

In [11]:
# if it is a model with one layer and one nueron 
model = nn.Sequential(nn.Linear(1, 1))

In [ ]:
#   losss and optimizer, here losss is criterion because loss is is not callable since it is a tensor object
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [14]:
xs = torch.tensor([[-1.0], [0.0], [1.0], [2.0], [3.0], [4.0]], dtype=torch.float32)

ys = torch.tensor([[-3.0], [-1.0], [1.0], [3.0], [5.0], [7.0]],dtype=torch.float32)

In [5]:
# Data
# Training features ['Years of experience', 'performance score', 'projects completed']
Features = torch.tensor([[1, 60, 2], [2, 65, 3], [3, 70, 4], [4, 72, 5], [5,  78,  6], [6,  82,  7], [7,  85,  8], [8,  88,  9], [9,  92, 10], [10, 95, 12]], dtype=torch.float32)

Salary = torch.tensor([[500], [700], [900], [1100], [1400], [1700], [2000], [2300], [2700], [3200]], dtype=torch.float32)

In [27]:
# TRianing
for _ in range(500):
    optimizer.zero_grad()
    output = model(xs)
    loss = criterion(output, ys)
    loss.backward()
    optimizer.step()
    print("Loss = ",loss)

Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  tensor(1.0604e-11, grad_fn=<MseLossBackward0>)
Loss =  te

In [28]:
# Predict
with torch.no_grad():
    print(model(torch.tensor([[10.0]], dtype=torch.float32)))

tensor([[19.0000]])


In [29]:
layer = model[0]

weights = layer.weight.data.numpy()
bias = layer.bias.data.numpy()

weights

array([[1.9999982]], dtype=float32)

In [30]:
bias

array([-0.99999595], dtype=float32)